import { defineHiddenObjectsStage } from "./schema.js";

export const hiddenPicnicStage = defineHiddenObjectsStage({
  id: "hidden_picnic_001",
  title: "Picnic Search",
  titleKo: "소풍 숨은그림",
  theme: "picnic",
  level: 1,
  estimatedMinutes: 3,
  scene: {
    image: "/assets/hidden-picnic-001.png",
    width: 1568,
    height: 1003,
    alt: "A sunny park picnic scene with a blanket, basket, kite, pond, and flowers.",
  },
  targets: [
    {
      id: "apple",
      word: "apple",
      meaning: "사과",
      phonetic: "/ˈæpəl/",
      sentence: "I found an apple.",
      translation: "사과를 찾았어요.",
      area: { type: "rect", x: 27.2, y: 58.4, w: 7.7, h: 9.7 },
      hint: "Look inside the picnic basket.",
    },
    {
      id: "kite",
      word: "kite",
      meaning: "연",
      phonetic: "/kaɪt/",
      sentence: "The kite is flying high.",
      translation: "연이 높이 날고 있어요.",
      area: { type: "rect", x: 78.5, y: 3.5, w: 10.5, h: 17 },
      hint: "Look up in the bright blue sky.",
    },
    {
      id: "book",
      word: "book",
      meaning: "책",
      phonetic: "/bʊk/",
      sentence: "The book is on the blanket.",
      translation: "책이 담요 위에 있어요.",
      area: { type: "rect", x: 6.4, y: 76, w: 21.5, h: 11.5 },
      hint: "Look near the corner of the picnic blanket.",
    },
    {
      id: "spoon",
      word: "spoon",
      meaning: "숟가락",
      phonetic: "/spuːn/",
      sentence: "The spoon is shiny.",
      translation: "숟가락이 반짝여요.",
      area: { type: "rect", x: 42.5, y: 76, w: 15, h: 7.5 },
      hint: "Look on top of the red blanket.",
    },
    {
      id: "duck",
      word: "duck",
      meaning: "오리",
      phonetic: "/dʌk/",
      sentence: "The duck is swimming.",
      translation: "오리가 헤엄치고 있어요.",
      area: { type: "rect", x: 78.3, y: 56.5, w: 13.5, h: 11 },
      hint: "Look in the water near the bridge.",
    },
    {
      id: "ball",
      word: "ball",
      meaning: "공",
      phonetic: "/bɔːl/",
      sentence: "The ball is in the grass.",
      translation: "공이 잔디 위에 있어요.",
      area: { type: "circle", x: 77, y: 82.3, r: 8.2 },
      hint: "Look in the grass beside the blanket.",
    },
  ],
});

export const defaultHiddenObjectsStage = hiddenPicnicStage;
